name: Test
on:
  push:
    branches:
      - main
  pull_request:
jobs:
  test:
    strategy:
      matrix:
        platform:
          - ubuntu-latest
          - macos-latest
          - windows-latest
    runs-on: ${{matrix.platform}}
    steps:
      - name: Install Go
        uses: actions/setup-go@v4
        with:
          go-version: 1.20.x
      - name: Checkout code
        uses: actions/checkout@v3
      - name: Lint
        uses: magefile/mage-action@v2
        with:
          version: latest
          args: lint
      - name: Doc Verify
        uses: magefile/mage-action@v2
        with:
          version: latest
          args: docVerify
      - name: Test
        uses: magefile/mage-action@v2
        with:
          version: latest
          args: test
      - name: Upload Coverage
        if: ${{ matrix.platform == 'ubuntu-latest' }}
        uses: codecov/codecov-action@v3
